services:
  postgres:
    image: postgres:16
    container_name: hook_runner_postgres
    environment:
      POSTGRES_USER: hook_user
      POSTGRES_PASSWORD: hook_password
      POSTGRES_DB: hook_runner_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: hook_runner_api
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: hook_user
      DB_PASSWORD: hook_password
      DB_NAME: hook_runner_db
    ports:
      - "8080:8080"

volumes:
  postgres_data: